### ISSUE TITLE
Outdated copyright  year

### ISSUE THREAD

**Issue by rsheasby** [i3/i3.github.io#59]
The copyright notice at the bottom of the page is still 2009. Not sure if this is deliberate, but as far as I understand(not a lawyer), any update to the website constitutes a new copyright and hence you guys should keep it updated. Most will do 2009-2018 or something like that.

**Comment by Airblader** [comment]
Hi,

Thanks for filing this issue. IANAL, but having a copyright on something doesn't require pointing it out anyway, so I would assume an outdated year shouldn't really matter either. 

We discussed this for other parts of the software some time ago and as far as I remember decided against keeping this up to date because it's just a bother, so I think we actually just removed the date. For the website I'd be happy about a PR that does something like "2009—present" or "since 2009" :-)

**Comment by ryan27968** [comment]
Yeah it's true the copyright notice is unnecessary, but a lot of people use it as a gauge of how up to date a site is. Is the site entirely static pages or is there some PHP or something like that powering it?

**Comment by Airblader** [comment]
It's mostly static, but assuming where you are going with this, I don't think this is worth putting effort into automatically putting in the last year.

I agree that just having 2009 there makes it look outdated, this I would propose a change as I mentioned above. I think there's much better ways to judge whether a project is active, though, such as the list of releases or commit activity on Github.

**Comment by ryan27968** [comment]
Fair enough.

**Comment by Airblader** [comment]
Would you like to submit a PR for it?

**Comment by ryan27968** [comment]
Sure. When I get a chance at least.

**Comment by ryan27968** [comment]
Out of curiosity, if I submitted a PR that does make it dynamic, would it be accepted? I know you don't feel it's worth the effort but is it the initial effort or the continued maintenance that worries you?

**Comment by Airblader** [comment]
If there's a trivial way to do it (and there very likely is one), that'd also be OK with me. There shouldn't be a continued maintenance effort if it's dynamic. :-)

**Comment by ryan27968** [comment]
Cool. Will submit pr soon.
